
export enum Effect {

    CHROMA_NONE = "CHROMA_NONE",

    CHROMA_STATIC = "CHROMA_STATIC",

    CHROMA_CUSTOM = "CHROMA_CUSTOM",

    CHROMA_CUSTOM2 = "CHROMA_CUSTOM2",

    CHROMA_CUSTOM_KEY = "CHROMA_CUSTOM_KEY"

}